name: Ansible Lint Checker for Push and Pull Request

on:
  push:
    branches:
      - '*' # Trigger on all branches
  pull_request:
    branches:
      - '*' # Trigger on all branches

jobs:
  ansible-lint:
    runs-on: ubuntu-latest # Use GitHub-hosted runner for simplicity
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch the entire history to detect changes

      # Step 2: Get modified files for pull requests
      - name: Get modified files for pull request
        id: get-changed-files-pull
        if: github.event_name == 'pull_request'
        run: |
          CHANGED_FILES=$(git diff --diff-filter=AM --name-only "${{ github.event.pull_request.base.sha }}" "${{ github.sha }}")
          echo "Changed files: $CHANGED_FILES"
          CHANGED_FILES_STR=$(echo "$CHANGED_FILES" | tr '\n' ' ')
          echo "changed-files=$CHANGED_FILES_STR" >> $GITHUB_ENV

      # Step 3: Get modified files for push events
      - name: Get modified files for push event
        id: get-changed-files-push
        if: github.event_name == 'push'
        run: |
          CHANGED_FILES=$(git diff --diff-filter=AM --name-only "${{ github.event.before }}" "${{ github.sha }}")
          echo "Changed files: $CHANGED_FILES"
          CHANGED_FILES_STR=$(echo "$CHANGED_FILES" | tr '\n' ' ')
          echo "changed-files=$CHANGED_FILES_STR" >> $GITHUB_ENV

      # Step 4: Segregate YAML files
      - name: Segregate YAML files
        id: segregate-files
        run: |
          YAML_FILES=""
          for file in $CHANGED_FILES_STR; do
            if [[ $file == *.yml || $file == *.yaml ]]; then
              YAML_FILES="$YAML_FILES $file"
            fi
          done
          echo "Segregated YAML files: $YAML_FILES"
          echo "yaml-files=$YAML_FILES" >> $GITHUB_OUTPUT

      # Step 5: Install ansible-lint
      - name: Install ansible-lint
        run: |
          pip install ansible-lint

      # Step 6: Scan Ansible playbooks
      - name: Scan Ansible playbooks
        run: |
          YAML_FILES=${{ steps.segregate-files.outputs.yaml-files }}
          if [ -n "$YAML_FILES" ]; then
            ansible-lint $YAML_FILES
          else
            echo "No YAML/YML files found, skipping ansible-lint"
          fi
